# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Documents/GitHub/graph-theory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Documents/GitHub/graph-theory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documents/GitHub/graph-theory/CMakeFiles /home/lucas/Documents/GitHub/graph-theory//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documents/GitHub/graph-theory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/linked-list/LinkedList.o: src/linked-list/LinkedList.cpp.o
.PHONY : src/linked-list/LinkedList.o

# target to build an object file
src/linked-list/LinkedList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/linked-list/LinkedList.cpp.o
.PHONY : src/linked-list/LinkedList.cpp.o

src/linked-list/LinkedList.i: src/linked-list/LinkedList.cpp.i
.PHONY : src/linked-list/LinkedList.i

# target to preprocess a source file
src/linked-list/LinkedList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/linked-list/LinkedList.cpp.i
.PHONY : src/linked-list/LinkedList.cpp.i

src/linked-list/LinkedList.s: src/linked-list/LinkedList.cpp.s
.PHONY : src/linked-list/LinkedList.s

# target to generate assembly for a file
src/linked-list/LinkedList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/linked-list/LinkedList.cpp.s
.PHONY : src/linked-list/LinkedList.cpp.s

src/linked-list/LinkedListNode.o: src/linked-list/LinkedListNode.cpp.o
.PHONY : src/linked-list/LinkedListNode.o

# target to build an object file
src/linked-list/LinkedListNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/linked-list/LinkedListNode.cpp.o
.PHONY : src/linked-list/LinkedListNode.cpp.o

src/linked-list/LinkedListNode.i: src/linked-list/LinkedListNode.cpp.i
.PHONY : src/linked-list/LinkedListNode.i

# target to preprocess a source file
src/linked-list/LinkedListNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/linked-list/LinkedListNode.cpp.i
.PHONY : src/linked-list/LinkedListNode.cpp.i

src/linked-list/LinkedListNode.s: src/linked-list/LinkedListNode.cpp.s
.PHONY : src/linked-list/LinkedListNode.s

# target to generate assembly for a file
src/linked-list/LinkedListNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/linked-list/LinkedListNode.cpp.s
.PHONY : src/linked-list/LinkedListNode.cpp.s

src/representation/AdjacencyList.o: src/representation/AdjacencyList.cpp.o
.PHONY : src/representation/AdjacencyList.o

# target to build an object file
src/representation/AdjacencyList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/AdjacencyList.cpp.o
.PHONY : src/representation/AdjacencyList.cpp.o

src/representation/AdjacencyList.i: src/representation/AdjacencyList.cpp.i
.PHONY : src/representation/AdjacencyList.i

# target to preprocess a source file
src/representation/AdjacencyList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/AdjacencyList.cpp.i
.PHONY : src/representation/AdjacencyList.cpp.i

src/representation/AdjacencyList.s: src/representation/AdjacencyList.cpp.s
.PHONY : src/representation/AdjacencyList.s

# target to generate assembly for a file
src/representation/AdjacencyList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/AdjacencyList.cpp.s
.PHONY : src/representation/AdjacencyList.cpp.s

src/representation/AdjacencyMatrix.o: src/representation/AdjacencyMatrix.cpp.o
.PHONY : src/representation/AdjacencyMatrix.o

# target to build an object file
src/representation/AdjacencyMatrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/AdjacencyMatrix.cpp.o
.PHONY : src/representation/AdjacencyMatrix.cpp.o

src/representation/AdjacencyMatrix.i: src/representation/AdjacencyMatrix.cpp.i
.PHONY : src/representation/AdjacencyMatrix.i

# target to preprocess a source file
src/representation/AdjacencyMatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/AdjacencyMatrix.cpp.i
.PHONY : src/representation/AdjacencyMatrix.cpp.i

src/representation/AdjacencyMatrix.s: src/representation/AdjacencyMatrix.cpp.s
.PHONY : src/representation/AdjacencyMatrix.s

# target to generate assembly for a file
src/representation/AdjacencyMatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/AdjacencyMatrix.cpp.s
.PHONY : src/representation/AdjacencyMatrix.cpp.s

src/representation/IncidenceMatrix.o: src/representation/IncidenceMatrix.cpp.o
.PHONY : src/representation/IncidenceMatrix.o

# target to build an object file
src/representation/IncidenceMatrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/IncidenceMatrix.cpp.o
.PHONY : src/representation/IncidenceMatrix.cpp.o

src/representation/IncidenceMatrix.i: src/representation/IncidenceMatrix.cpp.i
.PHONY : src/representation/IncidenceMatrix.i

# target to preprocess a source file
src/representation/IncidenceMatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/IncidenceMatrix.cpp.i
.PHONY : src/representation/IncidenceMatrix.cpp.i

src/representation/IncidenceMatrix.s: src/representation/IncidenceMatrix.cpp.s
.PHONY : src/representation/IncidenceMatrix.s

# target to generate assembly for a file
src/representation/IncidenceMatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/representation/IncidenceMatrix.cpp.s
.PHONY : src/representation/IncidenceMatrix.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/linked-list/LinkedList.o"
	@echo "... src/linked-list/LinkedList.i"
	@echo "... src/linked-list/LinkedList.s"
	@echo "... src/linked-list/LinkedListNode.o"
	@echo "... src/linked-list/LinkedListNode.i"
	@echo "... src/linked-list/LinkedListNode.s"
	@echo "... src/representation/AdjacencyList.o"
	@echo "... src/representation/AdjacencyList.i"
	@echo "... src/representation/AdjacencyList.s"
	@echo "... src/representation/AdjacencyMatrix.o"
	@echo "... src/representation/AdjacencyMatrix.i"
	@echo "... src/representation/AdjacencyMatrix.s"
	@echo "... src/representation/IncidenceMatrix.o"
	@echo "... src/representation/IncidenceMatrix.i"
	@echo "... src/representation/IncidenceMatrix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

